require 'nested_db/uploaders/instance_file_uploader'
require 'nested_db/models/physical_property'
require 'nested_db/models/virtual_property'
require 'nested_db/models/taxonomy'
require 'nested_db/models/instance'