require 'nested_db/uploaders/instance_file_uploader'
require 'nested_db/uploaders/instance_image_uploader'
require 'nested_db/uploaders/instance_version_uploader'
require 'nested_db/models/image_version'
require 'nested_db/models/callback_processing'